spring:
  datasource:
    master:
      username: root
      password: xieyc@mysql
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_master?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      username: root
      password: xieyc@mysql
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_slave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.yc.rw.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
#spring:
#  datasource:
#    master: # 写账户
#      jdbc-url: jdbc:mysql://localhost:3306/test_master?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#      username: root
#      password: xieyc@mysql
#    slave: # 只读账户
#      jdbc-url: jdbc:mysql://localhost:3306/test_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#      username: root
#      password: xieyc@mysql
