spring:
  datasource:
    master:
      username: root
      password: Xieyc@mysql1.>
      jdbc-url: jdbc:mysql://192.168.45.130:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      username: root
      password: Xieyc@mysql1.>
      jdbc-url: jdbc:mysql://192.168.45.131:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

#spring:
#  datasource:
#    master: # 写账户
#      jdbc-url: jdbc:mysql://localhost:3306/test_master?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#      username: root
#      password: xieyc@mysql
#    slave: # 只读账户
#      jdbc-url: jdbc:mysql://localhost:3306/test_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#      username: root
#      password: xieyc@mysql
